# Layout settings
defaults:
  -
    scope:
      path: "" 
    values:
      layout: "default"

  - # Exclude weekly posts
    scope:
      path: "_posts/*"  # Matches all files within _posts
      exclude: ["_posts/*.weekly.md"]  
    values:
      include: false

theme: jekyll-theme-minimal
title: Brahma's Personal Blog
description: Writing about Data Engineering problems and SQL
