# Site settings
title: Brahma's Personal Blog
description: Writing about Data Engineering problems and SQL
url: "https://brahma19.github.io/blog"
baseurl: "/blog"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Layout settings
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include all posts
include:
  - _posts

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Post settings
future: true  # Allow posts with future dates
